In [1]:
import sys
sys.path.append('../..')
import core
from config import *
import numpy as np
import cv2

In [2]:
H

array([[  9.40482450e-01,   4.97998904e-04,   7.96248223e+00],
       [ -1.89591995e-02,   9.40783691e-01,   3.64664430e+01],
       [ -6.78557578e-05,  -1.75746618e-05,   1.00000000e+00]])

In [3]:
h = np.array([[  0.50482450e00,   4.97998904e-04,   7.96248223e+00],
           [ -1.89591995e-02,   9.40783691e-01,   3.64664430e+01],
           [ -6.78557578e-05,  -1.75746618e-05,   1.00000000e+00]])

In [4]:
np.allclose(h, H, rtol=0, atol=0.4)

False

# Input Points of images to create homography

In [7]:
# Read source image.
im_src = cv2.imread('../../../SavedImages/2018-11-27-11-16-46_im.jpg')
# Four corners of the book in source image
pts_src = np.array([[208, 145], [280, 245], [471, 144],[508, 258]])


# Read destination image.
im_dst = cv2.imread('../../../SavedImages/2018-11-27-11-16-46_Ref.jpg')
# Four corners of the book in destination image.
pts_dst = np.array([[187, 174],[257, 272],[450, 166],[486, 280]])

# Calculate Homography
h, status = cv2.findHomography(pts_src, pts_dst)
print(h)

# Warp source image to destination based on homography
im_out = cv2.warpPerspective(im_src, h, (im_dst.shape[1],im_dst.shape[0]))

# Display images
#cv2.imshow("Source Image", im_src)
#cv2.imshow("Destination Image", im_dst)
#cv2.imshow("Warped Source Image", im_out)

cv2.waitKey(5000)

[[  9.71631909e-01  -1.54878188e-02  -1.46369618e+01]
 [ -3.33086365e-02   9.84860098e-01   3.64641936e+01]
 [ -4.17403109e-05  -5.89073275e-06   1.00000000e+00]]


-1

## Check NDVI map

In [3]:
[_,_,NIR] = cv2.split(im_out)
[_,_,R]   = cv2.split(im_dst)

NDVI = core.ndvi_map(R, NIR)
NDVI = cv2.cvtColor(NDVI, cv2.COLOR_RGB2BGR)
cv2.imshow("Warped Source Image", NDVI)
cv2.waitKey(0)

-1

# Different Points

In [8]:
# Read source image.
im_src = cv2.imread('../../../SavedImages/2018-11-27-11-16-46_im.jpg')
# Four corners of the book in source image
pts_src = np.array([[87,20], [350,16], [106,72],[348,75]])


# Read destination image.
im_dst = cv2.imread('../../../SavedImages/2018-11-27-11-16-46_Ref.jpg')
# Four corners of the book in destination image.
pts_dst = np.array([[63,58],[322,49],[84,109],[323,108]])

# Calculate Homography
h2, status = cv2.findHomography(pts_src, pts_dst)
print(h)
print(h2)

# Warp source image to destination based on homography
im_out = cv2.warpPerspective(im_src, h2, (im_dst.shape[1],im_dst.shape[0]))

# Display images
#cv2.imshow("Source Image", im_src)
#cv2.imshow("Destination Image", im_dst)
#cv2.imshow("Warped Source Image", im_out)

cv2.waitKey(5000)

[[  9.71631909e-01  -1.54878188e-02  -1.46369618e+01]
 [ -3.33086365e-02   9.84860098e-01   3.64641936e+01]
 [ -4.17403109e-05  -5.89073275e-06   1.00000000e+00]]
[[  9.65674440e-01   4.69856447e-02  -2.22296589e+01]
 [ -2.15046768e-02   9.81410102e-01   3.99883613e+01]
 [ -4.83138373e-05  -9.09645768e-06   1.00000000e+00]]


-1

## Check NDVI map

In [5]:
[_,_,NIR] = cv2.split(im_out)
[_,_,R]   = cv2.split(im_dst)

NDVI = core.ndvi_map(R, NIR)
NDVI = cv2.cvtColor(NDVI, cv2.COLOR_RGB2BGR)
cv2.imshow("Warped Source Image", NDVI)
cv2.waitKey(5000)

-1